// Categories & subcategories used by the interest picker.
// Comprehensive catalog covering popular classes across India and globally.
// Users can still add custom values if something is missing.

export interface CategoryGroup {
  name: string;
  subcategories: string[];
}

export const INTEREST_CATALOG: CategoryGroup[] = [
  {
    name: "Academics",
    subcategories: [
      "Maths", "Physics", "Chemistry", "Biology", "Zoology", "Botany",
      "English", "Hindi", "Sanskrit", "Marathi", "Bengali", "Tamil", "Telugu", "Kannada", "Malayalam", "Gujarati", "Punjabi", "Urdu",
      "History", "Geography", "Civics", "Political Science", "Sociology", "Psychology", "Philosophy",
      "Economics", "Business Studies", "Accounts", "Statistics",
      "Computer Science", "Information Technology", "Environmental Science",
      "Pre-Nursery / Nursery", "Primary School (Grade 1-5)", "Middle School (Grade 6-8)", "High School (Grade 9-10)", "Senior Secondary (Grade 11-12)",
      "CBSE", "ICSE", "IB", "IGCSE", "State Board",
      "Homework Help", "Handwriting Improvement", "Phonics", "Spelling Bee",
    ],
  },
  {
    name: "Test Prep & Competitive Exams",
    subcategories: [
      "JEE Main", "JEE Advanced", "NEET", "AIIMS", "BITSAT", "VITEEE",
      "CUET", "CLAT", "NIFT", "NID", "NATA",
      "UPSC (IAS/IPS)", "SSC CGL", "SSC CHSL", "Banking (IBPS/SBI)", "RBI Grade B", "RRB / Railways", "Defence (NDA/CDS/AFCAT)",
      "CA Foundation", "CA Inter", "CA Final", "CS", "CMA", "CFA", "FRM", "ACCA",
      "CAT", "XAT", "SNAP", "NMAT", "MAT", "GMAT", "GRE",
      "SAT", "ACT", "AP Exams", "LSAT", "MCAT",
      "IELTS", "TOEFL", "PTE", "Duolingo English Test", "OET",
      "Olympiads (Maths/Science)", "NTSE", "KVPY",
      "TET / CTET", "NET / JRF", "GATE",
    ],
  },
  {
    name: "Music - Vocals",
    subcategories: [
      "Hindustani Classical Vocals", "Carnatic Vocals", "Western Classical Vocals",
      "Bollywood Singing", "Ghazal", "Bhajan / Devotional", "Sufi Singing", "Folk Singing",
      "Pop / Rock Vocals", "Jazz Vocals", "Opera", "Choir Singing",
      "Playback Singing", "Rap / Hip Hop", "Beatboxing",
      "Voice Culture & Training",
    ],
  },
  {
    name: "Music - Instruments",
    subcategories: [
      "Guitar (Acoustic)", "Guitar (Electric)", "Bass Guitar", "Classical Guitar",
      "Piano", "Keyboard", "Synthesizer", "Harmonium", "Accordion",
      "Violin (Western)", "Violin (Carnatic)", "Viola", "Cello", "Double Bass",
      "Drums", "Cajon", "Djembe", "Tabla", "Mridangam", "Pakhawaj", "Dholak", "Dhol", "Ghatam", "Kanjira",
      "Flute (Bansuri)", "Western Flute", "Saxophone", "Clarinet", "Trumpet", "Trombone",
      "Sitar", "Sarod", "Veena", "Santoor", "Sarangi", "Shehnai", "Rudra Veena",
      "Ukulele", "Mandolin", "Banjo", "Harmonica",
      "Music Production / DAW", "DJing", "Sound Engineering", "Music Theory", "Songwriting / Composition",
    ],
  },
  {
    name: "Dance",
    subcategories: [
      "Bharatanatyam", "Kathak", "Kuchipudi", "Odissi", "Mohiniyattam", "Manipuri", "Sattriya",
      "Folk (Garba)", "Folk (Bhangra)", "Folk (Lavani)", "Folk (Bihu)", "Kalbeliya",
      "Bollywood", "Semi-Classical", "Lyrical",
      "Hip Hop", "Breaking / B-boying", "Popping", "Locking", "Krump",
      "Contemporary", "Jazz Dance", "Ballet", "Tap Dance", "Modern Dance",
      "Salsa", "Bachata", "Kizomba", "Tango", "Cha Cha", "Rumba", "Waltz", "Ballroom",
      "Zumba", "Aerobics Dance", "Belly Dance", "K-Pop Dance",
      "Choreography",
    ],
  },
  {
    name: "Sports & Athletics",
    subcategories: [
      "Cricket", "Football / Soccer", "Basketball", "Volleyball", "Hockey", "Rugby", "Baseball", "Handball",
      "Badminton", "Tennis", "Table Tennis", "Squash", "Pickleball",
      "Swimming", "Diving", "Water Polo", "Synchronized Swimming",
      "Athletics / Track & Field", "Cross Country", "Marathon Training",
      "Cycling", "Mountain Biking", "Skating (Roller)", "Skating (Inline)", "Ice Skating", "Skateboarding", "Surfing",
      "Gymnastics", "Rhythmic Gymnastics", "Calisthenics", "Parkour",
      "Golf", "Archery", "Shooting", "Equestrian / Horse Riding", "Polo",
      "Rowing", "Sailing", "Kayaking", "Scuba Diving",
      "Snooker / Billiards / Pool", "Bowling",
      "Chess", "Carrom", "Esports",
    ],
  },
  {
    name: "Martial Arts & Combat",
    subcategories: [
      "Karate", "Taekwondo", "Judo", "Jiu-Jitsu (BJJ)", "Aikido", "Kung Fu", "Wushu",
      "Boxing", "Kickboxing", "Muay Thai", "MMA",
      "Wrestling", "Kalaripayattu", "Silambam", "Gatka", "Krav Maga",
      "Self Defence (Women)", "Self Defence (Kids)",
      "Fencing", "Kendo", "Capoeira",
    ],
  },
  {
    name: "Yoga, Wellness & Meditation",
    subcategories: [
      "Hatha Yoga", "Ashtanga Yoga", "Vinyasa Flow", "Iyengar Yoga", "Kundalini Yoga", "Yin Yoga", "Power Yoga", "Aerial Yoga", "Acro Yoga", "Prenatal Yoga", "Kids Yoga", "Chair Yoga",
      "Pranayama / Breathwork", "Surya Namaskar",
      "Meditation", "Mindfulness", "Vipassana",
      "Art of Living (Sudarshan Kriya)", "Isha Yoga / Inner Engineering", "Heartfulness", "Sahaj Samadhi", "Transcendental Meditation",
      "Reiki", "Pranic Healing", "Sound Healing", "Crystal Healing", "Chakra Healing",
      "Tai Chi", "Qigong",
      "Ayurveda Basics", "Naturopathy",
    ],
  },
  {
    name: "Fitness & Health",
    subcategories: [
      "Personal Training", "Strength Training", "Weightlifting", "Powerlifting", "CrossFit",
      "HIIT", "Functional Fitness", "Bodyweight Training", "Pilates", "Barre",
      "Aerobics", "Step Aerobics", "Spinning / Indoor Cycling",
      "Zumba Fitness", "Dance Fitness",
      "Nutrition & Diet Planning", "Weight Loss Coaching", "Sports Nutrition",
      "Postnatal Fitness", "Senior Fitness", "Rehabilitation / Physiotherapy",
      "Running Coaching", "Triathlon Training",
    ],
  },
  {
    name: "Art & Craft",
    subcategories: [
      "Sketching / Pencil Drawing", "Charcoal Drawing", "Ink Drawing",
      "Painting (Acrylic)", "Painting (Oil)", "Painting (Watercolor)", "Painting (Gouache)", "Painting (Pastel)",
      "Madhubani", "Warli", "Tanjore Painting", "Kerala Mural", "Pichwai", "Gond Art", "Kalamkari",
      "Mandala Art", "Doodling", "Zentangle", "Calligraphy (Modern)", "Calligraphy (Arabic)", "Calligraphy (Devanagari)", "Hand Lettering",
      "Pottery / Ceramics", "Sculpture", "Clay Modelling", "Terracotta",
      "Origami", "Quilling", "Paper Mache",
      "Resin Art", "Fluid Art", "Glass Painting", "Bottle Art", "Fabric Painting",
      "Knitting", "Crochet", "Embroidery", "Cross Stitch", "Macrame", "Tie & Dye", "Block Printing",
      "Jewellery Making", "Candle Making", "Soap Making", "Resin Jewellery",
      "Photography (Basic)", "Photography (Portrait)", "Photography (Wildlife)", "Mobile Photography", "Photo Editing (Lightroom/Photoshop)",
      "2D Animation", "3D Animation", "Stop Motion", "Digital Illustration", "Procreate", "Comic / Manga Art",
      "Graphic Design", "UI/UX Design", "Logo Design", "Canva", "Figma", "Adobe Illustrator", "Adobe Photoshop",
      "Interior Design", "Fashion Design", "Sketching for Fashion",
      "Architecture Sketching", "AutoCAD", "SketchUp", "Blender (3D)",
      "Video Editing", "Filmmaking", "Cinematography", "VFX",
    ],
  },
  {
    name: "Coding & Tech",
    subcategories: [
      "Scratch (Kids)", "Block Coding", "Code.org",
      "Python", "Java", "C", "C++", "C#", "JavaScript", "TypeScript", "Go", "Rust", "Kotlin", "Swift", "PHP", "Ruby", "R",
      "HTML & CSS", "React", "Next.js", "Angular", "Vue", "Svelte", "Node.js", "Express",
      "Full Stack Web Development", "Frontend Development", "Backend Development",
      "Mobile App Development (Android)", "Mobile App Development (iOS)", "Flutter", "React Native",
      "Data Structures & Algorithms", "Competitive Programming",
      "Data Science", "Data Analytics", "SQL", "Power BI", "Tableau", "Excel (Advanced)", "Google Sheets",
      "Machine Learning", "Deep Learning", "AI / Generative AI", "Prompt Engineering", "LLMs / ChatGPT",
      "Cloud (AWS)", "Cloud (Azure)", "Cloud (GCP)", "DevOps", "Docker / Kubernetes", "Linux",
      "Cybersecurity", "Ethical Hacking", "Networking (CCNA)",
      "Blockchain", "Web3 / Solidity",
      "Game Development (Unity)", "Game Development (Unreal)", "Roblox Studio",
      "Robotics", "Arduino", "Raspberry Pi", "IoT", "Electronics",
      "MS Office", "Computer Basics", "Typing",
    ],
  },
  {
    name: "Hobbies & Brain Skills",
    subcategories: [
      "Rubik's Cube (3x3)", "Rubik's Cube (Advanced)", "Speed Cubing", "Pyraminx / Megaminx",
      "Abacus", "Vedic Maths", "Mental Maths", "UCMAS",
      "Memory Techniques", "Speed Reading",
      "Chess (Beginner)", "Chess (Advanced)", "Chess Openings", "FIDE Coaching",
      "Sudoku", "Puzzles", "Brain Gym",
      "Magic Tricks", "Card Tricks", "Mentalism",
      "Storytelling", "Creative Writing", "Poetry", "Journaling", "Blogging",
      "Public Speaking", "Debate", "Elocution", "MUN Training", "Anchoring",
      "Stand-up Comedy", "Improv",
      "Theatre / Acting", "Drama for Kids", "Mime", "Voice Acting", "Dubbing",
      "Astronomy", "Astrology", "Tarot Reading", "Numerology", "Palmistry", "Vastu", "Feng Shui",
      "Gardening", "Terrace Gardening", "Hydroponics", "Bonsai", "Ikebana", "Floral Arrangement",
      "Bird Watching", "Nature Journaling",
      "Lego / Building Blocks",
    ],
  },
  {
    name: "Languages",
    subcategories: [
      "English (Spoken)", "English (Grammar)", "Business English", "Accent Training",
      "Hindi", "Sanskrit", "Urdu",
      "Tamil", "Telugu", "Kannada", "Malayalam", "Marathi", "Bengali", "Gujarati", "Punjabi", "Odia", "Assamese",
      "Spanish", "French", "German", "Italian", "Portuguese", "Russian", "Dutch",
      "Mandarin Chinese", "Japanese", "Korean", "Thai", "Vietnamese",
      "Arabic", "Persian / Farsi", "Turkish", "Hebrew",
      "Sign Language (ISL)", "Sign Language (ASL)",
      "Latin", "Greek",
    ],
  },
  {
    name: "Cooking & Culinary",
    subcategories: [
      "Indian Cooking", "North Indian", "South Indian", "Bengali", "Gujarati", "Maharashtrian", "Punjabi", "Mughlai",
      "Continental", "Italian", "Mexican", "Thai", "Chinese", "Japanese / Sushi", "Korean", "Lebanese", "Mediterranean",
      "Baking (Cakes)", "Baking (Bread)", "Baking (Cookies)", "Eggless Baking", "Cake Decoration", "Fondant", "Chocolate Making",
      "Desserts & Pastries", "French Patisserie",
      "Vegan Cooking", "Keto Cooking", "Gluten-Free", "Healthy Cooking",
      "Tiffin / Lunchbox Ideas", "Kids Cooking", "Quick Meals",
      "Barista / Coffee Art", "Mixology / Bartending", "Tea Tasting",
      "Food Photography", "Food Styling", "Cloud Kitchen Setup",
    ],
  },
  {
    name: "Business, Finance & Career",
    subcategories: [
      "Stock Market", "Technical Analysis", "Fundamental Analysis", "Options Trading", "Crypto Trading", "Forex",
      "Mutual Funds", "Personal Finance", "Financial Planning", "Tax Planning",
      "Accounting (Tally)", "Accounting (QuickBooks)", "GST",
      "Digital Marketing", "SEO", "SEM / Google Ads", "Social Media Marketing", "Meta Ads", "Content Marketing", "Email Marketing", "Affiliate Marketing",
      "Copywriting", "Content Writing", "Technical Writing",
      "Entrepreneurship", "Startup Coaching", "Business Strategy", "Product Management", "Project Management (PMP)", "Agile / Scrum",
      "Sales Training", "Negotiation Skills",
      "Resume Building", "Interview Preparation", "LinkedIn Coaching", "Career Counselling",
      "Soft Skills", "Leadership", "Time Management", "Productivity",
      "Real Estate", "Insurance",
    ],
  },
  {
    name: "Lifestyle & Personal Growth",
    subcategories: [
      "Life Coaching", "NLP", "Confidence Building", "Personality Development",
      "Mental Health Counselling", "Anger Management", "Stress Management",
      "Relationship Coaching", "Parenting Coaching", "Pregnancy Coaching",
      "Etiquette & Grooming", "Image Consulting", "Wardrobe Styling",
      "Makeup Artistry", "Hair Styling", "Skincare", "Nail Art",
      "Mehendi / Henna", "Rangoli",
      "Fashion Styling",
    ],
  },
  {
    name: "Religious & Spiritual Studies",
    subcategories: [
      "Bhagavad Gita", "Vedas / Upanishads", "Ramayana", "Mahabharata",
      "Sanskrit Shlokas", "Vedic Chanting",
      "Quran Recitation", "Tajweed", "Arabic for Quran",
      "Bible Study",
      "Jainism", "Sikhism (Gurbani)", "Buddhism",
      "Pooja Vidhi", "Karma Kanda",
    ],
  },
];
