import { Listing, SlotKey } from "./types";

const s = (...keys: SlotKey[]) => keys;

export const SEED_LISTINGS: Listing[] = [
  {
    id: "seed-1",
    providerId: "seed-priya",
    providerName: "Priya's Math Lab",
    city: "Bengaluru",
    area: "Indiranagar",
    title: "Class 9–10 Maths Mastery",
    description: "Small-batch CBSE/ICSE maths coaching focused on conceptual clarity and problem solving.",
    category: "Academics",
    ageGroup: "Teens",
    mode: "Both",
    venue: "100 Ft Road, Indiranagar",
    price: "₹3,500 / month",
    trial: true,
    slots: s("Mon-17", "Wed-17", "Fri-17"),
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
  },
  {
    id: "seed-2",
    providerId: "seed-rhythm",
    providerName: "Rhythm Studio",
    city: "Bengaluru",
    area: "Koramangala",
    title: "Beginner Guitar for Adults",
    description: "Learn chords, strumming and your favourite songs in 8 weeks. No prior experience needed.",
    category: "Music",
    ageGroup: "Adults",
    mode: "Offline",
    venue: "5th Block, Koramangala",
    price: "₹4,000 / month",
    trial: true,
    slots: s("Tue-19", "Thu-19"),
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 14,
  },
  {
    id: "seed-3",
    providerId: "seed-leap",
    providerName: "Leap Dance Co.",
    city: "Mumbai",
    area: "Bandra",
    title: "Hip-Hop for Kids (8–12)",
    description: "High-energy hip-hop classes building rhythm, coordination and confidence.",
    category: "Dance",
    ageGroup: "Kids",
    mode: "Offline",
    venue: "Linking Road, Bandra West",
    price: "₹2,800 / month",
    trial: true,
    slots: s("Sat-10", "Sun-10"),
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
  },
  {
    id: "seed-4",
    providerId: "seed-codekids",
    providerName: "CodeKids Academy",
    city: "Bengaluru",
    area: "HSR Layout",
    title: "Scratch & Python for Kids",
    description: "Learn programming through games and projects. Live online classes with tiny batches.",
    category: "Coding",
    ageGroup: "Kids",
    mode: "Online",
    price: "₹3,200 / month",
    trial: true,
    slots: s("Mon-18", "Wed-18", "Sat-11"),
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 21,
  },
  {
    id: "seed-5",
    providerId: "seed-zen",
    providerName: "Zen Flow Yoga",
    city: "Delhi",
    area: "Saket",
    title: "Morning Hatha Yoga",
    description: "Start your day with breath, stretch and stillness. All levels welcome.",
    category: "Yoga",
    ageGroup: "Adults",
    mode: "Both",
    venue: "Select Citywalk area",
    price: "₹2,500 / month",
    trial: true,
    slots: s("Mon-7", "Tue-7", "Wed-7", "Thu-7", "Fri-7"),
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
  },
  {
    id: "seed-6",
    providerId: "seed-brush",
    providerName: "Brushstrokes Atelier",
    city: "Pune",
    area: "Kothrud",
    title: "Watercolour Weekends",
    description: "Cozy weekend workshops exploring landscapes, florals and abstract washes.",
    category: "Art",
    ageGroup: "All",
    mode: "Offline",
    venue: "Karve Road, Kothrud",
    price: "₹1,500 / session",
    trial: false,
    slots: s("Sat-15", "Sun-11"),
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
  {
    id: "seed-7",
    providerId: "seed-acekick",
    providerName: "AceKick Football Academy",
    city: "Hyderabad",
    area: "Gachibowli",
    title: "Junior Football Training",
    description: "FIFA-licensed coaches running drills, matches and fitness for ages 7–14.",
    category: "Sports",
    ageGroup: "Kids",
    mode: "Offline",
    venue: "Gachibowli Stadium grounds",
    price: "₹3,000 / month",
    trial: true,
    slots: s("Tue-17", "Thu-17", "Sat-9"),
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 12,
  },
  {
    id: "seed-8",
    providerId: "seed-lingua",
    providerName: "Lingua Live",
    city: "Other",
    area: "Online",
    title: "Spoken French — A1 to A2",
    description: "Conversational French taught by native speakers. Live online, twice a week.",
    category: "Languages",
    ageGroup: "Adults",
    mode: "Online",
    price: "₹4,500 / month",
    trial: true,
    slots: s("Mon-20", "Thu-20"),
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  } as unknown as Listing,
  {
    id: "seed-9",
    providerId: "seed-littlestars",
    providerName: "Little Stars Music",
    city: "Bengaluru",
    area: "Whitefield",
    title: "Piano for Beginners (Kids)",
    description: "Trinity-aligned piano lessons for kids ages 6–12. Recitals every quarter.",
    category: "Music",
    ageGroup: "Kids",
    mode: "Offline",
    venue: "Whitefield Main Road",
    price: "₹3,800 / month",
    trial: true,
    slots: s("Wed-16", "Sat-10"),
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: "seed-10",
    providerId: "seed-mindforge",
    providerName: "MindForge Tutors",
    city: "Chennai",
    area: "Adyar",
    title: "JEE Foundation — Physics",
    description: "Build a rock-solid physics base for JEE. Weekly tests, doubt clearing, mentorship.",
    category: "Academics",
    ageGroup: "Teens",
    mode: "Both",
    venue: "Adyar Signal",
    price: "₹6,000 / month",
    trial: false,
    slots: s("Mon-19", "Wed-19", "Sat-17"),
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 8,
  },
];
